// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/calculate-age": {
            "post": {
                "description": "Calculates exact age, next birthday, and life summary based on date of birth and a reference date.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Age Calculator",
                "parameters": [
                    {
                        "description": "Age Calculation Request (Dates in YYYY-MM-DD format)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.AgeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Age Result",
                        "schema": {
                            "$ref": "#/definitions/converter.AgeCalculationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/calculate-bmi": {
            "post": {
                "description": "Calculates Body Mass Index (BMI) based on weight and height",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "BMI Calculator",
                "parameters": [
                    {
                        "description": "BMI Calculation Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.BMIRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "BMI Result",
                        "schema": {
                            "$ref": "#/definitions/api.BMIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/calculate-percentage": {
            "post": {
                "description": "Performs any percentage operation (X% of Y, what %, change, increase, decrease,\n\n**Supported operations (` + "`" + `operation` + "`" + ` field):**\n- ` + "`" + `percent_of` + "`" + `              (value1 = percent, value2 = number)\n- ` + "`" + `what_percent` + "`" + `            (value1 = part, value2 = whole)\n- ` + "`" + `percent_change` + "`" + `          (value1 = old, value2 = new)\n- ` + "`" + `percent_increase` + "`" + `        (value1 = number, value2 = percent)\n- ` + "`" + `percent_decrease` + "`" + `        (value1 = number, value2 = percent)\n- ` + "`" + `reverse_percent` + "`" + `         (value1 = final, value2 = percent)\n- ` + "`" + `is_percent_of_what` + "`" + `      (value1 = part, value2 = percent)\n- ` + "`" + `percent_difference` + "`" + `      (value1 = a, value2 = b)\n- ` + "`" + `add_percent_points` + "`" + `      (value1 = p1%, value2 = p2%)\n- ` + "`" + `subtract_percent_points` + "`" + ` (value1 = p1%, value2 = p2%)\n- ` + "`" + `discount` + "`" + `                (value1 = price, value2 = discount%)\n- ` + "`" + `markup` + "`" + `                  (value1 = cost, value2 = markup%)\n- ` + "`" + `profit_loss` + "`" + `             (value1 = cost, value2 = selling)\n- ` + "`" + `percent_to_fraction` + "`" + `     (value1 = percent)\n- ` + "`" + `fraction_to_percent` + "`" + `     (value1 = numerator, value2 = denominator)\n- ` + "`" + `decimal_to_percent` + "`" + `      (value1 = decimal)\n- ` + "`" + `compound_percent` + "`" + `        (value1 = base, value2 = percent, value3 = periods)\n- ` + "`" + `marks_percentage` + "`" + `        (value1 = obtained, value2 = total)\n- ` + "`" + `cgpa_to_percent` + "`" + `         (value1 = cgpa; uses CBSE factor 9.5)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Percentage Calculator"
                ],
                "summary": "Percentage Calculator",
                "parameters": [
                    {
                        "description": "Percentage Calculation Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.PercentageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Percentage Result",
                        "schema": {
                            "$ref": "#/definitions/converter.PercentageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request - invalid operation or parameters",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/convert": {
            "post": {
                "description": "Converts any supported file type to another supported file type dynamically.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "summary": "Universal File Converter",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Source file type (e.g. txt, csv, json, pdf, docx, jpg, png)",
                        "name": "fromType",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Target file type (e.g. txt, csv, json, pdf, docx, jpg, png)",
                        "name": "toType",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "The file to convert",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The converted file",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request or unsupported combination",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/convert-measurement": {
            "post": {
                "description": "Converts measurements between different units (e.g., meters to feet)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Measurement Converter",
                "parameters": [
                    {
                        "description": "Conversion Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.MeasurementRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Conversion Result",
                        "schema": {
                            "$ref": "#/definitions/api.MeasurementResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/convert-numeral": {
            "post": {
                "description": "Converts between numeral systems like binary, decimal, octal, hexadecimal.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Numeral System Converter",
                "parameters": [
                    {
                        "description": "Conversion Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.NumeralRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Conversion Result",
                        "schema": {
                            "$ref": "#/definitions/api.NumeralResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/convert-pdf-size": {
            "post": {
                "description": "Upload a PDF and convert it toward a requested target file size.\n\n**Ranges:**\n- Compression: target must be between **10 KB** and **400 MB**.\n- Expansion:   target must be between **10 KB** and **6000 KB**.\n- Uploaded file must not exceed **600 MB**.\n\n**Response headers:**\n- ` + "`" + `X-Conversion-Target-Met` + "`" + `: ` + "`" + `true` + "`" + ` if the target was reached, ` + "`" + `false` + "`" + ` if the smallest achievable size was returned.\n- ` + "`" + `X-Conversion-Target-Size` + "`" + `: the requested target in bytes.\n- ` + "`" + `X-Conversion-Actual-Size` + "`" + `: the actual output size in bytes.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/pdf"
                ],
                "tags": [
                    "PDF Converter"
                ],
                "summary": "Compress or expand PDF",
                "parameters": [
                    {
                        "type": "file",
                        "description": "PDF file (max 600 MB)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "compression or expand",
                        "name": "conversionType",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "KB or MB",
                        "name": "dataType",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Target file size",
                        "name": "targetSize",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Converted PDF",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request - invalid parameters",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/convert-railway": {
            "post": {
                "description": "Converts between 12-hour AM/PM and 24-hour Indian Railway time format.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Railway Time Converter",
                "parameters": [
                    {
                        "description": "Railway Conversion Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/converter.RailwayConversionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Conversion Result",
                        "schema": {
                            "$ref": "#/definitions/converter.RailwayConversionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/convert-time": {
            "post": {
                "description": "Converts date and time from any location/time zone to any other location/time zone accurately.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Universal Time Converter",
                "parameters": [
                    {
                        "description": "Time Conversion Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/converter.TimeConversionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Conversion Result",
                        "schema": {
                            "$ref": "#/definitions/converter.TimeConversionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.AgeRequest": {
            "type": "object",
            "properties": {
                "dob": {
                    "description": "format: YYYY-MM-DD",
                    "type": "string"
                },
                "today": {
                    "description": "format: YYYY-MM-DD",
                    "type": "string"
                }
            }
        },
        "api.BMIRequest": {
            "type": "object",
            "properties": {
                "height": {
                    "type": "number"
                },
                "heightUnit": {
                    "description": "e.g., \"meters\", \"centimeters\", \"feet\", \"inches\"",
                    "type": "string"
                },
                "weight": {
                    "type": "number"
                },
                "weightUnit": {
                    "description": "e.g., \"kilograms\", \"pounds\"",
                    "type": "string"
                }
            }
        },
        "api.BMIResponse": {
            "type": "object",
            "properties": {
                "bmi": {
                    "type": "number"
                },
                "category": {
                    "type": "string"
                }
            }
        },
        "api.MeasurementRequest": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "fromUnit": {
                    "type": "string"
                },
                "toUnit": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "api.MeasurementResponse": {
            "type": "object",
            "properties": {
                "result": {
                    "type": "number"
                }
            }
        },
        "api.NumeralRequest": {
            "type": "object",
            "properties": {
                "fromBase": {
                    "type": "string"
                },
                "toBase": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "api.NumeralResponse": {
            "type": "object",
            "properties": {
                "result": {
                    "type": "string"
                }
            }
        },
        "api.PercentageRequest": {
            "type": "object",
            "properties": {
                "operation": {
                    "type": "string"
                },
                "value1": {
                    "type": "number"
                },
                "value2": {
                    "type": "number"
                },
                "value3": {
                    "type": "number"
                }
            }
        },
        "converter.AgeCalculationResponse": {
            "type": "object",
            "properties": {
                "age": {
                    "$ref": "#/definitions/converter.AgeResult"
                },
                "nextBirthday": {
                    "$ref": "#/definitions/converter.NextBirthday"
                },
                "summary": {
                    "$ref": "#/definitions/converter.Summary"
                }
            }
        },
        "converter.AgeResult": {
            "type": "object",
            "properties": {
                "days": {
                    "type": "integer"
                },
                "months": {
                    "type": "integer"
                },
                "years": {
                    "type": "integer"
                }
            }
        },
        "converter.NextBirthday": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "day": {
                    "type": "integer"
                },
                "dayOfWeek": {
                    "type": "string"
                },
                "daysRemaining": {
                    "type": "integer"
                },
                "month": {
                    "type": "integer"
                },
                "monthsRemaining": {
                    "type": "integer"
                }
            }
        },
        "converter.PercentageResponse": {
            "type": "object",
            "properties": {
                "extra": {
                    "type": "object",
                    "additionalProperties": true
                },
                "formatted": {
                    "type": "string"
                },
                "operation": {
                    "type": "string"
                },
                "result": {
                    "type": "number"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "converter.RailwayConversionRequest": {
            "type": "object",
            "properties": {
                "ampm": {
                    "description": "\"AM\" or \"PM\"",
                    "type": "string"
                },
                "direction": {
                    "description": "\"12to24\" or \"24to12\"",
                    "type": "string"
                },
                "hour": {
                    "type": "integer"
                },
                "minute": {
                    "type": "integer"
                }
            }
        },
        "converter.RailwayConversionResponse": {
            "type": "object",
            "properties": {
                "ampm": {
                    "type": "string"
                },
                "hour_12": {
                    "type": "integer"
                },
                "hour_24": {
                    "type": "integer"
                },
                "minute": {
                    "type": "integer"
                }
            }
        },
        "converter.Summary": {
            "type": "object",
            "properties": {
                "days": {
                    "type": "integer"
                },
                "hours": {
                    "type": "integer"
                },
                "minutes": {
                    "type": "integer"
                },
                "months": {
                    "type": "integer"
                },
                "weeks": {
                    "type": "integer"
                },
                "years": {
                    "type": "integer"
                }
            }
        },
        "converter.TimeConversionRequest": {
            "type": "object",
            "properties": {
                "ambiguous_policy": {
                    "description": "Policy for ambiguous times (fall back): \"first\" (default) or \"second\"",
                    "type": "string"
                },
                "day": {
                    "type": "integer"
                },
                "dest_tz": {
                    "description": "e.g., \"Asia/Tokyo\"",
                    "type": "string"
                },
                "hour": {
                    "type": "integer"
                },
                "minute": {
                    "type": "integer"
                },
                "month": {
                    "type": "integer"
                },
                "non_existent_policy": {
                    "description": "Policy for non-existent times (spring forward): \"forward\" (default, shifts forward) or \"error\"",
                    "type": "string"
                },
                "second": {
                    "type": "integer"
                },
                "source_tz": {
                    "description": "e.g., \"America/New_York\"",
                    "type": "string"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "converter.TimeConversionResponse": {
            "type": "object",
            "properties": {
                "dest_offset": {
                    "type": "string"
                },
                "dest_time_local": {
                    "description": "ISO 8601 with offset",
                    "type": "string"
                },
                "dest_time_utc": {
                    "description": "ISO 8601",
                    "type": "string"
                },
                "dest_zone_name": {
                    "type": "string"
                },
                "is_next_day": {
                    "type": "boolean"
                },
                "is_prev_day": {
                    "type": "boolean"
                },
                "resolution": {
                    "$ref": "#/definitions/converter.TimeResolution"
                },
                "source_offset": {
                    "description": "e.g. \"-04:00\"",
                    "type": "string"
                },
                "source_time_local": {
                    "description": "ISO 8601 with offset",
                    "type": "string"
                },
                "source_time_utc": {
                    "description": "ISO 8601",
                    "type": "string"
                },
                "source_zone_name": {
                    "description": "e.g. \"EDT\"",
                    "type": "string"
                },
                "warning": {
                    "type": "string"
                }
            }
        },
        "converter.TimeResolution": {
            "type": "string",
            "enum": [
                "normal",
                "ambiguous",
                "non-existent"
            ],
            "x-enum-varnames": [
                "ResolutionNormal",
                "ResolutionAmbiguous",
                "ResolutionNonExistent"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "File Converter API",
	Description:      "Utility Microservice for converting files.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
