// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/calculate-bmi": {
            "post": {
                "description": "Calculates Body Mass Index (BMI) based on weight and height",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "BMI Calculator",
                "parameters": [
                    {
                        "description": "BMI Calculation Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.BMIRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "BMI Result",
                        "schema": {
                            "$ref": "#/definitions/api.BMIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/convert": {
            "post": {
                "description": "Converts any supported file type to another supported file type dynamically.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "summary": "Universal File Converter",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Source file type (e.g. txt, csv, json, pdf, docx, jpg, png)",
                        "name": "fromType",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Target file type (e.g. txt, csv, json, pdf, docx, jpg, png)",
                        "name": "toType",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "The file to convert",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The converted file",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request or unsupported combination",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/convert-measurement": {
            "post": {
                "description": "Converts measurements between different units (e.g., meters to feet)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Measurement Converter",
                "parameters": [
                    {
                        "description": "Conversion Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.MeasurementRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Conversion Result",
                        "schema": {
                            "$ref": "#/definitions/api.MeasurementResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/convert-numeral": {
            "post": {
                "description": "Converts between numeral systems like binary, decimal, octal, hexadecimal.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Numeral System Converter",
                "parameters": [
                    {
                        "description": "Conversion Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.NumeralRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Conversion Result",
                        "schema": {
                            "$ref": "#/definitions/api.NumeralResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/convert-railway": {
            "post": {
                "description": "Converts between 12-hour AM/PM and 24-hour Indian Railway time format.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Railway Time Converter",
                "parameters": [
                    {
                        "description": "Railway Conversion Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/converter.RailwayConversionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Conversion Result",
                        "schema": {
                            "$ref": "#/definitions/converter.RailwayConversionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/convert-time": {
            "post": {
                "description": "Converts date and time from any location/time zone to any other location/time zone accurately.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Universal Time Converter",
                "parameters": [
                    {
                        "description": "Time Conversion Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/converter.TimeConversionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Conversion Result",
                        "schema": {
                            "$ref": "#/definitions/converter.TimeConversionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.BMIRequest": {
            "type": "object",
            "properties": {
                "height": {
                    "type": "number"
                },
                "heightUnit": {
                    "description": "e.g., \"meters\", \"centimeters\", \"feet\", \"inches\"",
                    "type": "string"
                },
                "weight": {
                    "type": "number"
                },
                "weightUnit": {
                    "description": "e.g., \"kilograms\", \"pounds\"",
                    "type": "string"
                }
            }
        },
        "api.BMIResponse": {
            "type": "object",
            "properties": {
                "bmi": {
                    "type": "number"
                },
                "category": {
                    "type": "string"
                }
            }
        },
        "api.MeasurementRequest": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "fromUnit": {
                    "type": "string"
                },
                "toUnit": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "api.MeasurementResponse": {
            "type": "object",
            "properties": {
                "result": {
                    "type": "number"
                }
            }
        },
        "api.NumeralRequest": {
            "type": "object",
            "properties": {
                "fromBase": {
                    "type": "string"
                },
                "toBase": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "api.NumeralResponse": {
            "type": "object",
            "properties": {
                "result": {
                    "type": "string"
                }
            }
        },
        "converter.RailwayConversionRequest": {
            "type": "object",
            "properties": {
                "ampm": {
                    "description": "\"AM\" or \"PM\"",
                    "type": "string"
                },
                "direction": {
                    "description": "\"12to24\" or \"24to12\"",
                    "type": "string"
                },
                "hour": {
                    "type": "integer"
                },
                "minute": {
                    "type": "integer"
                }
            }
        },
        "converter.RailwayConversionResponse": {
            "type": "object",
            "properties": {
                "ampm": {
                    "type": "string"
                },
                "hour_12": {
                    "type": "integer"
                },
                "hour_24": {
                    "type": "integer"
                },
                "minute": {
                    "type": "integer"
                }
            }
        },
        "converter.TimeConversionRequest": {
            "type": "object",
            "properties": {
                "ambiguous_policy": {
                    "description": "Policy for ambiguous times (fall back): \"first\" (default) or \"second\"",
                    "type": "string"
                },
                "day": {
                    "type": "integer"
                },
                "dest_tz": {
                    "description": "e.g., \"Asia/Tokyo\"",
                    "type": "string"
                },
                "hour": {
                    "type": "integer"
                },
                "minute": {
                    "type": "integer"
                },
                "month": {
                    "type": "integer"
                },
                "non_existent_policy": {
                    "description": "Policy for non-existent times (spring forward): \"forward\" (default, shifts forward) or \"error\"",
                    "type": "string"
                },
                "second": {
                    "type": "integer"
                },
                "source_tz": {
                    "description": "e.g., \"America/New_York\"",
                    "type": "string"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "converter.TimeConversionResponse": {
            "type": "object",
            "properties": {
                "dest_offset": {
                    "type": "string"
                },
                "dest_time_local": {
                    "description": "ISO 8601 with offset",
                    "type": "string"
                },
                "dest_time_utc": {
                    "description": "ISO 8601",
                    "type": "string"
                },
                "dest_zone_name": {
                    "type": "string"
                },
                "is_next_day": {
                    "type": "boolean"
                },
                "is_prev_day": {
                    "type": "boolean"
                },
                "resolution": {
                    "$ref": "#/definitions/converter.TimeResolution"
                },
                "source_offset": {
                    "description": "e.g. \"-04:00\"",
                    "type": "string"
                },
                "source_time_local": {
                    "description": "ISO 8601 with offset",
                    "type": "string"
                },
                "source_time_utc": {
                    "description": "ISO 8601",
                    "type": "string"
                },
                "source_zone_name": {
                    "description": "e.g. \"EDT\"",
                    "type": "string"
                },
                "warning": {
                    "type": "string"
                }
            }
        },
        "converter.TimeResolution": {
            "type": "string",
            "enum": [
                "normal",
                "ambiguous",
                "non-existent"
            ],
            "x-enum-varnames": [
                "ResolutionNormal",
                "ResolutionAmbiguous",
                "ResolutionNonExistent"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "File Converter API",
	Description:      "Utility Microservice for converting files.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
